apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-restaurant-application
  labels:
    app: deployment-restaurant-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-restaurant-application
  template:
    metadata:
      labels:
        app: deployment-restaurant-application
    spec:    
      containers:
        - name: deployment-restaurant-application
          image: lpugliese/fiap-clean-restaurant-application:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: secret-application-postgres-db
                  key: db_url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-application-postgres-db
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-application-postgres-db
                  key: db_password
            - name: DB_DRIVER
              valueFrom:
                secretKeyRef:
                  name: secret-application-postgres-db
                  key: db_driver
            - name: DB_DIALECT
              valueFrom:
                secretKeyRef:
                  name: secret-application-postgres-db
                  key: db_dialect
          readinessProbe:
            httpGet:
              path: /lanchonete/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /lanchonete/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            requests:
              cpu: 700m
              memory: 600Mi
            limits:
              cpu: 1400m
              memory: 2Gi