apiVersion: v1
kind: Secret
metadata:
  name: secret-application-postgres-db
type: Opaque
stringData:
    db_url: "jdbc:postgresql://postgres-db:5432/fiap"
    db_user: "postgres"
    db_password: "postgres"
    db_driver: "org.postgresql.Driver"
    db_dialect: "org.hibernate.dialect.PostgreSQLDialect"